//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.12.14 at 05:27:24 PM GMT 
//


package uk.ac.soton.ecs.forge.restws.representations;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="coffee" type="{}Coffee" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="beverage" type="{}Beverage" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="receipt" type="{}Receipt"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "coffee",
    "beverage",
    "receipt"
})
@XmlRootElement(name = "trayResponse")
public class TrayResponse {

    protected List<Coffee> coffee;
    protected List<Beverage> beverage;
    @XmlElement(required = true)
    protected Receipt receipt;

    /**
     * Gets the value of the coffee property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the coffee property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCoffee().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Coffee }
     * 
     * 
     */
    public List<Coffee> getCoffee() {
        if (coffee == null) {
            coffee = new ArrayList<Coffee>();
        }
        return this.coffee;
    }

    /**
     * Gets the value of the beverage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the beverage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBeverage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Beverage }
     * 
     * 
     */
    public List<Beverage> getBeverage() {
        if (beverage == null) {
            beverage = new ArrayList<Beverage>();
        }
        return this.beverage;
    }

    /**
     * Gets the value of the receipt property.
     * 
     * @return
     *     possible object is
     *     {@link Receipt }
     *     
     */
    public Receipt getReceipt() {
        return receipt;
    }

    /**
     * Sets the value of the receipt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Receipt }
     *     
     */
    public void setReceipt(Receipt value) {
        this.receipt = value;
    }

}
